### ISSUE TITLE
Add Support For Handshake via Custom ACME Server 

### ISSUE THREAD

**Issue by flikites** [RunOnFlux/flux-mini-fdm#1]
I would like to be able to use a custom ACME server to generate certificates specifically for the use with Handshake Domain names. 

https://acme.htools.work/directory

More information related to this ACME server: https://acme.htools.work/

From my understanding it is completely compatible with certbot.

**Comment by flikites** [comment]
Might be a cool idea to create an environment variable to specify the ACME server to use if they want to bypass the default (LetsEncrypt)

**Comment by alihm** [comment]
Haven't worked with Handshake domains yet, not sure if bypassing the default ACME server would make it work with Handshake domains. Needs some digging.

**Comment by flikites** [comment]
I'm very well versed in Handshake Domains. I've been testing them extensively. That ACME server is all I use to get going cert wise.Combined with my own Authoritative DNS server.  ---- On Sun, 11 Dec 2022 14:25:18 -0500  ***@***.***  wrote ----
Haven't worked with Handshake domains yet, not sure if bypassing the default ACME server would make it work with Handshake domains. Needs some digging.

**Comment by alihm** [comment]
Cool, how are the renewals done? do we need to pass ACME server on renewal command?

**Comment by alihm** [comment]
Added it to dev branch, not tested yet, you need to pass  `-e ACME=yourserver` in docker run. Let me know how it goes.

**Comment by flikites** [comment]
They are renewed once per year. The user gets an email with the TLSA record that they set in their DNS server when setting the A record for the server hosting the mini FDM. I will test the dev branch later tonight and report back accordingly. I appreciate your help here.  ---- On Sun, 11 Dec 2022 15:02:59 -0500  ***@***.***  wrote ----
Cool, how are the renewals done? do we need to pass ACME server on renewal command?

**Comment by flikites** [comment]
It works!

**Comment by alihm** [comment]
Cool, so we have handshake support now?

**Comment by flikites** [comment]
Yes! I will work on writing up a detailed guide on everything that goes into deploying with Handshake and Flux using this new image.I'll also detail in the guide how Handshake names can be resolved. ---- On Mon, 12 Dec 2022 10:27:48 -0500  ***@***.***  wrote ----
Cool, so we have handshake support now?

**Comment by alihm** [comment]
Cool, please let me know when the guide is ready or put a PR on readme file, We can have a section for handshake domains in readme. Thanks.

**Comment by flikites** [comment]
Will do. Right now I'm working through some kinks on the last part which is getting SSL to work properly when the TLSA record is set.  

When I have everything set at the DNS level and try to visit the site I get: ```ERR_SSL_PROTOCOL_ERROR```

I'm going to take a closer look at the current config of HA Proxy and see if I need to add or change anything there.

**Comment by flikites** [comment]
I'm not too familiar with HA Proxy:

This is what my working configuration looks like in NGINX.

``` 
upstream backend {
 server 1.2.3.4;
}

server {
  listen 80;
  server_name load.snipd;

  listen 443 ssl;
  ssl_certificate         /etc/ssl/snipd.crt;
  ssl_certificate_key     /etc/ssl/snipd.key;
  ssl_session_cache shared:SSL:20m;
  ssl_session_timeout 10m;

  ssl_prefer_server_ciphers       on;
  ssl_protocols                   TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                     ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;

  add_header Strict-Transport-Security "max-age=31536000";

  location / {
    proxy_pass http://backend;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

}
```
If you could, please update the dev branch ha proxy config file to include the equivalent of the below headers:

```
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by alihm** [comment]
Adding these will forward real IP:
```
option forwardfor
option http-server-close
```
Also added samples for X-Forwarded-Fo and Host headers in the config of dev branch.

**Comment by flikites** [comment]
Thank you. Gonna do some testing now and see if I can work through the SSL error.

**Comment by alihm** [comment]
actually, we can also add the option to choose between haproxy or nginx as load-balancer. do you know a nice template for nginx load-balancer?

**Comment by flikites** [comment]
That would be great. The config I sent you above should work for load balancer just place the other IP addresses under 1.2.3.4 in the upstream.

 upstream backend {
 server 1.2.3.4;
 server 1.2.3.4;
 server 1.2.3.4;
}

**Comment by flikites** [comment]
I just tested this NGINX configuration file and everything works properly including when the TLSA record is set. 

``` 
upstream backend {
 server 76.237.86.176:31337;
 server 154.12.235.62:31337;
}

server {
  listen 80;
  server_name api.snipd;

  listen 443 ssl;
  ssl_certificate         /etc/ssl/certs/snipd.crt;
  ssl_certificate_key     /etc/ssl/certs/snipd.key;
  ssl_session_cache shared:SSL:20m;
  ssl_session_timeout 10m;

  ssl_prefer_server_ciphers       on;
  ssl_protocols                   TLSv1.2;
  ssl_ciphers                     ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
  
  add_header Strict-Transport-Security "max-age=31536000";

  location / {
    proxy_pass http://backend;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

}
```

**Comment by flikites** [comment]
@alihm I'm looking through my reverse proxy deployment with Caddy as well, and the one thing I'm noticing that is different between my NGINX & Caddy Config and the HA Proxy Confg is that HA Proxy is storing the cert as a pem file and not as .crt and .key files. 

While NGINX and Caddy store the files separately and not as a PEM file. (Caddy uses the ACME server)

The TLSA record is a hash of the public key cert, and not a hash of the pem cert.

Another possible solution may be to force TCP mode for https, I tried configuring Ha Proxy using information from below, but ran into errors due to not knowing the exact syntax for tcp-request: but its likely the issue I outlined above with the mismatch in hash.

https://serverfault.com/questions/236496/haproxy-not-passing-ssl-traffic-in-tcp-mode-unknown-protocol

https://serverfault.com/questions/1029930/having-trouble-with-tcp-mode-on-haproxy-running-on-opnsense

https://www.haproxy.com/blog/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/

**Comment by flikites** [comment]
Still working through this:

I was able to get a site to resolve securely with a handshake name by removing ```tune.ssl.default-dh-param 4096``` from the SSL options in the config.

What other numbers can be used in place of 4096 for this parameter?

I'd like to test further.

I'm still running into spotty resolution of the secure handshake name, so going to keep working the kinks out for now, the technical write up is coming along, but I won't furnish it until I know that users with have a good experience resolving their  sites built on Handshake + Flux.

**Comment by flikites** [comment]
Found the documentation: http://docs.haproxy.org/2.6/configuration.html#tune.ssl.default-dh-param

**Comment by flikites** [comment]
In the end to get Full SSL support for Handshake I needed to add this to the end of the https bind:

```alpn h3,h2,http/1.1```

I will submit a pull request and close this.
